Vagrant.configure("2") do |c|
  c.vm.box = "opscode-precise32"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_precise32_chef-provisionerless.box"
  c.vm.hostname = "default-precise32.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
